# Generated by Django 2.1.13 on 2020-11-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='关联文章'),
        ),
    ]
