# Generated by Django 2.1.13 on 2020-11-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201109_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commit_self',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Commit', verbose_name='子评论'),
        ),
    ]
